ALTER TABLE tasklist
    ADD COLUMN created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN created_by  UUID,
    ADD COLUMN updated_at  TIMESTAMP WITHOUT TIME ZONE,
    ADD COLUMN updated_by  UUID,
    ADD COLUMN deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    ADD COLUMN deleted_by  UUID,
    ADD COLUMN version     INTEGER NOT NULL DEFAULT 0;
